### ISSUE TITLE
Vigra installation issue

### ISSUE THREAD

**Issue by vibhavagarwal5** [gramuah/ccnn#8]
I am trying to run this code with python 3 but it turns out that its uses python2.7. With Python2.7, I am not to install caffe. I tried converting your code from 2.7 to 3 as well to fix the caffe issue but I am not able to fix the Vigra installation issue.

**Comment by Anzoteh96** [comment]
Try `2to3 -w [basically all python files]`, which basically converts all files from Python2 to Python3.

**Comment by pasquale90** [comment]
What made my life easier was miniconda... Both Vigra and caffe were able to installed in a python 2.7 compatible conda environment using two snippets of code. 
```
conda create yourEnv python=2.7
conda activate yourEnv
.....(install other dependencies)
conda install -c conda-forge vigra
conda install -c conda-forge caffe  
```
